/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <clib/exec_protos.h>
#include <clib/intuition_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/utility_protos.h>
#include <string.h>

#include <pragmas/exec_pragmas.h>
#include <pragmas/intuition_pragmas.h>
#include <pragmas/gadtools_pragmas.h>
#include <pragmas/graphics_pragmas.h>
#include <pragmas/utility_pragmas.h>

#include "instrprop.h"

struct Screen         *Scr = NULL;
UBYTE                 *PubScreenName = NULL;
APTR                   VisualInfo = NULL;
struct Window         *CPPWindowWnd = NULL;
struct Window         *HelpWnd = NULL;
struct Gadget         *CPPWindowGList = NULL;
struct Menu           *CPPWindowMenus = NULL;
struct Menu           *HelpMenus = NULL;
struct IntuiMessage    CPPWindowMsg;
struct IntuiMessage    HelpMsg;
struct Gadget         *CPPWindowGadgets[29];
UWORD                  CPPWindowLeft = 93;
UWORD                  CPPWindowTop = 116;
UWORD                  CPPWindowWidth = 353;
UWORD                  CPPWindowHeight = 109;
UWORD                  HelpLeft = 577;
UWORD                  HelpTop = 14;
UWORD                  HelpWidth = 110;
UWORD                  HelpHeight = 10;
UBYTE                 *CPPWindowWdt = (UBYTE *)"CAMD Patch Properties";
UBYTE                 *HelpWdt = (UBYTE *)"Help!";

struct TextAttr topaz8 = {
	( STRPTR )"topaz.font", 8, 0x00, 0x01 };

struct NewMenu CPPWindowNewMenu[] = {
	NM_TITLE, (STRPTR)"Menu", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Reset All Controllers", NULL, 0, 2L, (APTR)CPPWindowResetAllControllers,
	NM_ITEM, (STRPTR)"Local Keyboard On", NULL, 0, 0L, (APTR)CPPWindowLocalKeyboardOn,
	NM_ITEM, (STRPTR)"Local Keyboard Off", NULL, 0, 0L, (APTR)CPPWindowLocalKeyboardOff,
	NM_ITEM, (STRPTR)"All Notes Off", NULL, 0, 0L, (APTR)CPPWindowAllNotesOff,
	NM_ITEM, (STRPTR)"All Sounds Off", NULL, 0, 0L, (APTR)CPPWindowAllSoundsOff,
	NM_END, NULL, NULL, 0, 0L, NULL };

struct NewMenu HelpNewMenu[] = {
	NM_TITLE, (STRPTR)"Project", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Load RA+o", NULL, 0, 0L, (APTR)HelpItem0,
	NM_ITEM, (STRPTR)"Save RA+w", NULL, 0, 0L, (APTR)HelpItem1,
	NM_ITEM, (STRPTR)"Save As RA+W", NULL, 0, 0L, (APTR)HelpItem2,
	NM_ITEM, (STRPTR)"Set Colors RA+C", NULL, 0, 0L, (APTR)HelpItem3,
	NM_ITEM, (STRPTR)"About", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Radium", NULL, 0, 0L, (APTR)HelpItem4,
	NM_SUB, (STRPTR)"--------", NULL, 0, 0L, (APTR)HelpItem5,
	NM_SUB, (STRPTR)"Made by Kjetil S. Matheussen", NULL, 0, 0L, (APTR)HelpItem6,
	NM_SUB, (STRPTR)"k.s.matheusse@notam.uio.no", NULL, 0, 0L, (APTR)HelpItem7,
	NM_SUB, (STRPTR)"--------", NULL, 0, 0L, (APTR)HelpItem8,
	NM_SUB, (STRPTR)"http://www.notam.uio.no/", NULL, 0, 0L, (APTR)HelpItem9,
	NM_SUB, (STRPTR)"~kjetism/radium/index.cgi", NULL, 0, 0L, (APTR)HelpItem10,
	NM_ITEM, (STRPTR)"Quit RA+q", NULL, 0, 0L, (APTR)HelpItem11,
	NM_TITLE, (STRPTR)"Edit", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Window", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Config - RA + c", NULL, 0, 0L, (APTR)HelpItem12,
	NM_ITEM, (STRPTR)"Block", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Insert - Ctrl+i", NULL, 0, 0L, (APTR)HelpItem13,
	NM_SUB, (STRPTR)"Delete - Ctrl+r", NULL, 0, 0L, (APTR)HelpItem14,
	NM_SUB, (STRPTR)"Append - Ctrl+f", NULL, 0, 0L, (APTR)HelpItem15,
	NM_SUB, (STRPTR)"Properties - RA + b", NULL, 0, 0L, (APTR)HelpItem16,
	NM_SUB, (STRPTR)"Minimize - Ctrl+m", NULL, 0, 0L, (APTR)HelpItem17,
	NM_ITEM, (STRPTR)"Track", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Insert - LAlt + i", NULL, 0, 0L, (APTR)HelpItem18,
	NM_SUB, (STRPTR)"Delete - LAlt + r", NULL, 0, 0L, (APTR)HelpItem19,
	NM_SUB, (STRPTR)"--------------", NULL, 0, 0L, (APTR)HelpItem20,
	NM_SUB, (STRPTR)"Minimize - LAlt+m", NULL, 0, 0L, (APTR)HelpItem21,
	NM_SUB, (STRPTR)"Notelength - LAlt+n", NULL, 0, 0L, (APTR)HelpItem22,
	NM_SUB, (STRPTR)"--------------", NULL, 0, 0L, (APTR)HelpItem23,
	NM_SUB, (STRPTR)"Mute - LAlt+o", NULL, 0, 0L, (APTR)HelpItem24,
	NM_SUB, (STRPTR)"On - LAlt+o", NULL, 0, 0L, (APTR)HelpItem25,
	NM_SUB, (STRPTR)"Solo - LAlt+LS+o", NULL, 0, 0L, (APTR)HelpItem26,
	NM_SUB, (STRPTR)"All On - Ctrl+o", NULL, 0, 0L, (APTR)HelpItem27,
	NM_ITEM, (STRPTR)"Lines", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Add - LS + Return", NULL, 0, 0L, (APTR)HelpItem28,
	NM_ITEM, (STRPTR)"Note", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Keyboard Up octave - TAB", NULL, 0, 0L, (APTR)HelpItem29,
	NM_SUB, (STRPTR)"Keyboard Down octave - Shift + TAB", NULL, 0, 0L, (APTR)HelpItem30,
	NM_SUB, (STRPTR)"---------------", NULL, 0, 0L, (APTR)HelpItem31,
	NM_SUB, (STRPTR)"Add Destructive - <key>", NULL, 0, 0L, (APTR)HelpItem32,
	NM_SUB, (STRPTR)"Add - RS+<key>", NULL, 0, 0L, (APTR)HelpItem33,
	NM_SUB, (STRPTR)"Delete - Del", NULL, 0, 0L, (APTR)HelpItem34,
	NM_SUB, (STRPTR)"Stop Notes - Del", NULL, 0, 0L, (APTR)HelpItem35,
	NM_SUB, (STRPTR)"---------------", NULL, 0, 0L, (APTR)HelpItem36,
	NM_SUB, (STRPTR)"Del line - BS", NULL, 0, 0L, (APTR)HelpItem37,
	NM_SUB, (STRPTR)"Insert line - LAlt+BS", NULL, 0, 0L, (APTR)HelpItem38,
	NM_ITEM, (STRPTR)"Velocities", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Del - Del", NULL, 0, 0L, (APTR)HelpItem39,
	NM_SUB, (STRPTR)"Def Pos - Return", NULL, 0, 0L, (APTR)HelpItem40,
	NM_SUB, (STRPTR)"Increase - RS + Right", NULL, 0, 0L, (APTR)HelpItem41,
	NM_SUB, (STRPTR)"Increase 10 - RS+RAlt+Right", NULL, 0, 0L, (APTR)HelpItem42,
	NM_SUB, (STRPTR)"Decrease - RS + Left", NULL, 0, 0L, (APTR)HelpItem43,
	NM_SUB, (STRPTR)"Decrease 10 - RS+Ralt + Left", NULL, 0, 0L, (APTR)HelpItem44,
	NM_ITEM, (STRPTR)"FX", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Add - RM", NULL, 0, 0L, (APTR)HelpItem45,
	NM_SUB, (STRPTR)"Edit - LM and move", NULL, 0, 0L, (APTR)HelpItem46,
	NM_SUB, (STRPTR)"Remove - LM and move far", NULL, 0, 0L, (APTR)HelpItem47,
	NM_ITEM, (STRPTR)"Tempos", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Add LPB - Return", NULL, 0, 0L, (APTR)HelpItem48,
	NM_SUB, (STRPTR)"Add BPM - Return", NULL, 0, 0L, (APTR)HelpItem49,
	NM_ITEM, (STRPTR)"Transpose", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Range up 1 - LA + u", NULL, 0, 0L, (APTR)HelpItem50,
	NM_SUB, (STRPTR)"Range up 12 - LA + U", NULL, 0, 0L, (APTR)HelpItem51,
	NM_SUB, (STRPTR)"Range down 1 - LA + d", NULL, 0, 0L, (APTR)HelpItem52,
	NM_SUB, (STRPTR)"Range down 12 - LA + U", NULL, 0, 0L, (APTR)HelpItem53,
	NM_SUB, (STRPTR)"Track up 1 - LAlt + u", NULL, 0, 0L, (APTR)HelpItem54,
	NM_SUB, (STRPTR)"Track up 12 - LAlt + U", NULL, 0, 0L, (APTR)HelpItem55,
	NM_SUB, (STRPTR)"Track down 1 - LAlt + d", NULL, 0, 0L, (APTR)HelpItem56,
	NM_SUB, (STRPTR)"Track down 12 - Lalt + D", NULL, 0, 0L, (APTR)HelpItem57,
	NM_SUB, (STRPTR)"Block up 1 - LS + u", NULL, 0, 0L, (APTR)HelpItem58,
	NM_SUB, (STRPTR)"Block up 12 - LS + U", NULL, 0, 0L, (APTR)HelpItem59,
	NM_SUB, (STRPTR)"Block down 1 - LS + u", NULL, 0, 0L, (APTR)HelpItem60,
	NM_SUB, (STRPTR)"Block down 12 - LS + D", NULL, 0, 0L, (APTR)HelpItem61,
	NM_ITEM, (STRPTR)"Undo", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Undo - RA + u", NULL, 0, 0L, (APTR)HelpItem62,
	NM_SUB, (STRPTR)"Redo - RA + U", NULL, 0, 0L, (APTR)HelpItem63,
	NM_SUB, (STRPTR)"Set buffer - RA + RAlt + u", NULL, 0, 0L, (APTR)HelpItem64,
	NM_ITEM, (STRPTR)"Quantitize", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Block - Ctrl+q", NULL, 0, 0L, (APTR)HelpItem65,
	NM_SUB, (STRPTR)"Track - LAlt + q", NULL, 0, 0L, (APTR)HelpItem66,
	NM_SUB, (STRPTR)"Range - LA+q", NULL, 0, 0L, (APTR)HelpItem67,
	NM_ITEM, (STRPTR)"Midi", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Input On/Off - ESC", NULL, 0, 0L, (APTR)HelpItem68,
	NM_ITEM, (STRPTR)"Invert", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Block - Ctrl + 8", NULL, 0, 0L, (APTR)HelpItem69,
	NM_SUB, (STRPTR)"Track - LAlt + 8", NULL, 0, 0L, (APTR)HelpItem70,
	NM_SUB, (STRPTR)"Range - LA + 8", NULL, 0, 0L, (APTR)HelpItem71,
	NM_ITEM, (STRPTR)"Backwards", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Block - Ctrl + 9", NULL, 0, 0L, (APTR)HelpItem72,
	NM_SUB, (STRPTR)"Track - LAlt + 9", NULL, 0, 0L, (APTR)HelpItem73,
	NM_SUB, (STRPTR)"Range - LA + 9", NULL, 0, 0L, (APTR)HelpItem74,
	NM_TITLE, (STRPTR)"Zoom", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Line", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Zoom more - LS + Down", NULL, 0, 0L, (APTR)HelpItem75,
	NM_SUB, (STRPTR)"Zoom less - LS + Up", NULL, 0, 0L, (APTR)HelpItem76,
	NM_SUB, (STRPTR)"Zoom zoom - ATAB", NULL, 0, 0L, (APTR)HelpItem77,
	NM_SUB, (STRPTR)"Cancel zoom - 1", NULL, 0, 0L, (APTR)HelpItem78,
	NM_ITEM, (STRPTR)"All", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Zoom in - M1", NULL, 0, 0L, (APTR)HelpItem79,
	NM_SUB, (STRPTR)"Zoom in more - LA + M1", NULL, 0, 0L, (APTR)HelpItem80,
	NM_SUB, (STRPTR)"Zoom out - M2", NULL, 0, 0L, (APTR)HelpItem81,
	NM_SUB, (STRPTR)"Zoom out more - LA + M2", NULL, 0, 0L, (APTR)HelpItem82,
	NM_SUB, (STRPTR)"Cancel zoom - M3", NULL, 0, 0L, (APTR)HelpItem83,
	NM_TITLE, (STRPTR)"Orientation", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Block", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Next - f", NULL, 0, 0L, (APTR)HelpItem84,
	NM_SUB, (STRPTR)"Previous - a", NULL, 0, 0L, (APTR)HelpItem85,
	NM_SUB, (STRPTR)"Next in playlist - F", NULL, 0, 0L, (APTR)HelpItem86,
	NM_SUB, (STRPTR)"Previous in playlist - A", NULL, 0, 0L, (APTR)HelpItem87,
	NM_ITEM, (STRPTR)"Track", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Next Sub - Right", NULL, 0, 0L, (APTR)HelpItem88,
	NM_SUB, (STRPTR)"Prev Sub - Left", NULL, 0, 0L, (APTR)HelpItem89,
	NM_SUB, (STRPTR)"Next - RAlt + Right", NULL, 0, 0L, (APTR)HelpItem90,
	NM_SUB, (STRPTR)"Prev - RAlt + Left", NULL, 0, 0L, (APTR)HelpItem91,
	NM_ITEM, (STRPTR)"Line", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Down - Down", NULL, 0, 0L, (APTR)HelpItem92,
	NM_SUB, (STRPTR)"Up - Up", NULL, 0, 0L, (APTR)HelpItem93,
	NM_SUB, (STRPTR)"Down 10 - RS + Down", NULL, 0, 0L, (APTR)HelpItem94,
	NM_SUB, (STRPTR)"Up 10 - RS + Up", NULL, 0, 0L, (APTR)HelpItem95,
	NM_SUB, (STRPTR)"Next Note - RAlt + Down", NULL, 0, 0L, (APTR)HelpItem96,
	NM_SUB, (STRPTR)"Prev Note - RAlt + Up", NULL, 0, 0L, (APTR)HelpItem97,
	NM_SUB, (STRPTR)"Pos 0/4  - F6", NULL, 0, 0L, (APTR)HelpItem98,
	NM_SUB, (STRPTR)"Pos 1/4  - F7", NULL, 0, 0L, (APTR)HelpItem99,
	NM_SUB, (STRPTR)"Pos 2/4  - F8", NULL, 0, 0L, (APTR)HelpItem100,
	NM_SUB, (STRPTR)"Pos 3/4  - F9", NULL, 0, 0L, (APTR)HelpItem101,
	NM_SUB, (STRPTR)"Pos 4/4  - F10", NULL, 0, 0L, (APTR)HelpItem102,
	NM_TITLE, (STRPTR)"Instrument", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Add - HELP", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"(Chooses the instrument", NULL, 0, 0L, (APTR)HelpItem103,
	NM_SUB, (STRPTR)"To use for the", NULL, 0, 0L, (APTR)HelpItem104,
	NM_SUB, (STRPTR)"current track.)", NULL, 0, 0L, (APTR)HelpItem105,
	NM_SUB, (STRPTR)" ", NULL, 0, 0L, (APTR)HelpItem106,
	NM_SUB, (STRPTR)"(Or press right mouse)", NULL, 0, 0L, (APTR)HelpItem107,
	NM_TITLE, (STRPTR)"ClipBoard", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Block", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Copy - LS + c", NULL, 0, 0L, (APTR)HelpItem108,
	NM_SUB, (STRPTR)"Paste - LS + v", NULL, 0, 0L, (APTR)HelpItem109,
	NM_ITEM, (STRPTR)"Track", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Copy - LA + c", NULL, 0, 0L, (APTR)HelpItem110,
	NM_SUB, (STRPTR)"Cut - LA + x", NULL, 0, 0L, (APTR)HelpItem111,
	NM_SUB, (STRPTR)"Paste - LA + v", NULL, 0, 0L, (APTR)HelpItem112,
	NM_ITEM, (STRPTR)"Range", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Mark - LA + b", NULL, 0, 0L, (APTR)HelpItem113,
	NM_SUB, (STRPTR)"Cancel Range - LA + z", NULL, 0, 0L, (APTR)HelpItem114,
	NM_SUB, (STRPTR)"Cut - LA + x", NULL, 0, 0L, (APTR)HelpItem115,
	NM_SUB, (STRPTR)"Copy - LA + c", NULL, 0, 0L, (APTR)HelpItem116,
	NM_SUB, (STRPTR)"Paste - LA + v", NULL, 0, 0L, (APTR)HelpItem117,
	NM_TITLE, (STRPTR)"Play", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Song", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"From Start - RS+RAlt + Space", NULL, 0, 0L, (APTR)HelpItem118,
	NM_SUB, (STRPTR)"From Curr - RS + Space", NULL, 0, 0L, (APTR)HelpItem119,
	NM_ITEM, (STRPTR)"Block", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"From top - RA + Space", NULL, 0, 0L, (APTR)HelpItem120,
	NM_SUB, (STRPTR)"From curr - RS + Space", NULL, 0, 0L, (APTR)HelpItem121,
	NM_ITEM, (STRPTR)"Stop - Space", NULL, 0, 0L, (APTR)HelpItem122,
	NM_TITLE, (STRPTR)"Help", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Keys", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"RA = Right Amiga", NULL, 0, 0L, (APTR)HelpItem123,
	NM_SUB, (STRPTR)"LA = Right Amiga", NULL, 0, 0L, (APTR)HelpItem124,
	NM_SUB, (STRPTR)"RS = Right Shift", NULL, 0, 0L, (APTR)HelpItem125,
	NM_SUB, (STRPTR)"LS = Left Shift", NULL, 0, 0L, (APTR)HelpItem126,
	NM_SUB, (STRPTR)"RALT = Right Alt", NULL, 0, 0L, (APTR)HelpItem127,
	NM_SUB, (STRPTR)"LALT = Left Alt", NULL, 0, 0L, (APTR)HelpItem128,
	NM_SUB, (STRPTR)"BS = BackSpace", NULL, 0, 0L, (APTR)HelpItem129,
	NM_SUB, (STRPTR)"RM = Right Mouse", NULL, 0, 0L, (APTR)HelpItem130,
	NM_SUB, (STRPTR)"LM = Left Mouse", NULL, 0, 0L, (APTR)HelpItem131,
	NM_SUB, (STRPTR)"ATAB = The key above TAB", NULL, 0, 0L, (APTR)HelpItem132,
	NM_SUB, (STRPTR)"M1 = The right key to m", NULL, 0, 0L, (APTR)HelpItem133,
	NM_SUB, (STRPTR)"M2 = The right key to M1", NULL, 0, 0L, (APTR)HelpItem134,
	NM_SUB, (STRPTR)"M3 = The right key to M2", NULL, 0, 0L, (APTR)HelpItem135,
	NM_ITEM, (STRPTR)"Menues does not work!", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"The menues are just a help", NULL, 0, 0L, (APTR)HelpItem136,
	NM_SUB, (STRPTR)"to remember the", NULL, 0, 0L, (APTR)HelpItem137,
	NM_SUB, (STRPTR)"keybindings.", NULL, 0, 0L, (APTR)HelpItem138,
	NM_END, NULL, NULL, 0, 0L, NULL };

UWORD CPPWindowGTypes[] = {
	STRING_KIND,
	BUTTON_KIND,
	STRING_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	SLIDER_KIND,
	SLIDER_KIND,
	SLIDER_KIND,
	SLIDER_KIND,
	SLIDER_KIND,
	SLIDER_KIND,
	SLIDER_KIND,
	SLIDER_KIND,
	SLIDER_KIND,
	SLIDER_KIND,
	SLIDER_KIND,
	SLIDER_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	SLIDER_KIND
};

struct NewGadget CPPWindowNGad[] = {
	4, 3, 245, 17, NULL, NULL, GD_name, 0, NULL, (APTR)nameClicked,
	252, 3, 53, 16, (UBYTE *)"New", NULL, GD_New, PLACETEXT_IN, NULL, (APTR)NewClicked,
	3, 49, 68, 13, (UBYTE *)"Port", NULL, GD_Cluster, PLACETEXT_ABOVE, NULL, (APTR)ClusterClicked,
	163, 49, 45, 13, (UBYTE *)"MSB", NULL, GD_MSB, PLACETEXT_ABOVE, NULL, (APTR)MSBClicked,
	257, 49, 48, 13, (UBYTE *)"Preset", NULL, GD_Preset, PLACETEXT_ABOVE, NULL, (APTR)PresetClicked,
	209, 49, 47, 13, (UBYTE *)"LSB", NULL, GD_LSB, PLACETEXT_ABOVE, NULL, (APTR)LSBClicked,
	309, 3, 15, 73, NULL, NULL, GD_Volume, 0, NULL, (APTR)VolumeClicked,
	32, 65, 246, 11, NULL, NULL, GD_Pan, 0, NULL, (APTR)PanClicked,
	328, 3, 15, 73, NULL, NULL, GD_Velocity, 0, NULL, (APTR)VelocityClicked,
	28, 81, 59, 11, NULL, NULL, GD_Cr, 0, NULL, (APTR)CrClicked,
	112, 81, 63, 11, NULL, NULL, GD_Re, 0, NULL, (APTR)ReClicked,
	200, 81, 60, 11, NULL, NULL, GD_At, 0, NULL, (APTR)AtClicked,
	286, 81, 57, 10, NULL, NULL, GD_Rl, 0, NULL, (APTR)RlClicked,
	28, 94, 59, 11, NULL, NULL, GD_Cu, 0, NULL, (APTR)CuClicked,
	112, 94, 63, 11, NULL, NULL, GD_Rs, 0, NULL, (APTR)RsClicked,
	201, 94, 60, 11, NULL, NULL, GD_Va, 0, NULL, (APTR)VaClicked,
	287, 94, 57, 11, NULL, NULL, GD_Mo, 0, NULL, (APTR)MoClicked,
	4, 22, 301, 12, NULL, NULL, GD_Number, 0, NULL, (APTR)NumberClicked,
	4, 81, 21, 11, (UBYTE *)"Cr", NULL, GD_B1, PLACETEXT_IN, NULL, (APTR)B1Clicked,
	4, 94, 22, 11, (UBYTE *)"Cu", NULL, GD_B5, PLACETEXT_IN, NULL, (APTR)B5Clicked,
	89, 81, 21, 11, (UBYTE *)"Re", NULL, GD_B2, PLACETEXT_IN, NULL, (APTR)B2Clicked,
	90, 94, 21, 11, (UBYTE *)"Rs", NULL, GD_B6, PLACETEXT_IN, NULL, (APTR)B6Clicked,
	178, 81, 21, 11, (UBYTE *)"At", NULL, GD_B3, PLACETEXT_IN, NULL, (APTR)B3Clicked,
	177, 94, 21, 11, (UBYTE *)"Va", NULL, GD_B7, PLACETEXT_IN, NULL, (APTR)B7Clicked,
	264, 81, 21, 11, (UBYTE *)"Rl", NULL, GD_B4, PLACETEXT_IN, NULL, (APTR)B4Clicked,
	264, 94, 21, 11, (UBYTE *)"Mo", NULL, GD_B8, PLACETEXT_IN, NULL, (APTR)B8Clicked,
	4, 65, 26, 11, NULL, NULL, GD_Panonoff, 0, NULL, (APTR)PanonoffClicked,
	280, 65, 26, 11, NULL, NULL, GD_Volumeonoff, 0, NULL, (APTR)VolumeonoffClicked,
	74, 49, 87, 13, NULL, NULL, GD_Channel, 0, NULL, (APTR)ChannelClicked
};

ULONG CPPWindowGTags[] = {
	(GTST_String), (ULONG)"No Patch", (GTST_MaxChars), 50, (GA_Disabled), TRUE, (TAG_DONE),
	(TAG_DONE),
	(GTST_MaxChars), 256, (GA_Disabled), TRUE, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGCENTER), (GA_Disabled), TRUE, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGCENTER), (GA_Disabled), TRUE, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (STRINGA_Justification), (GACT_STRINGCENTER), (GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Max), 127, (GTSL_Level), 100, (PGA_Freedom), LORIENT_VERT, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Max), 127, (GTSL_Level), 64, (GTSL_LevelPlace), (PLACETEXT_ABOVE), (PGA_Freedom), LORIENT_HORIZ, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Max), 127, (GTSL_Level), 100, (PGA_Freedom), LORIENT_VERT, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (TAG_DONE),
	(GTSL_Max), 127, (GTSL_Level), 100, (PGA_Freedom), LORIENT_HORIZ, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Max), 127, (GTSL_Level), 100, (PGA_Freedom), LORIENT_HORIZ, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Max), 127, (GTSL_Level), 100, (PGA_Freedom), LORIENT_HORIZ, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Max), 127, (GTSL_Level), 100, (PGA_Freedom), LORIENT_HORIZ, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Max), 127, (GTSL_Level), 100, (PGA_Freedom), LORIENT_HORIZ, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Max), 127, (GTSL_Level), 100, (GTSL_LevelPlace), (PLACETEXT_RIGHT), (PGA_Freedom), LORIENT_HORIZ, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Max), 127, (GTSL_Level), 100, (PGA_Freedom), LORIENT_HORIZ, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Max), 127, (GTSL_Level), 100, (PGA_Freedom), LORIENT_HORIZ, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Max), 0, (PGA_Freedom), LORIENT_HORIZ, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GTSL_Min), 1, (GTSL_Max), 16, (GTSL_MaxLevelLen), 12, (GTSL_LevelFormat), (ULONG)"Channel %ld", (GTSL_LevelPlace), (PLACETEXT_ABOVE), (PGA_Freedom), LORIENT_HORIZ, (GA_Immediate), TRUE, (GA_RelVerify), TRUE, (GA_Disabled), TRUE, (TAG_DONE)
};

int SetupScreen( void )
{
	if ( ! ( Scr = LockPubScreen( PubScreenName )))
		return( 1L );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		UnlockPubScreen( NULL, Scr );
		Scr = NULL;
	}
}

int HandleCPPWindowIDCMP( void )
{
	struct IntuiMessage	*m;
	struct MenuItem		*n;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( CPPWindowWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&CPPWindowMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( CPPWindowMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( CPPWindowWnd );
				GT_EndRefresh( CPPWindowWnd, TRUE );
				break;

			case	IDCMP_GADGETUP:
			case	IDCMP_GADGETDOWN:
				func = ( void * )(( struct Gadget * )CPPWindowMsg.IAddress )->UserData;
				running = func();
				break;

			case	IDCMP_MENUPICK:
				while( CPPWindowMsg.Code != MENUNULL ) {
					n = ItemAddress( CPPWindowMenus, CPPWindowMsg.Code );
					func = (void *)(GTMENUITEM_USERDATA( n ));
					running = func();
					CPPWindowMsg.Code = n->NextSelect;
				}
				break;
		}
	}
	return( running );
}

int OpenCPPWindowWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		offx = Scr->WBorLeft, offy = Scr->WBorTop + Scr->RastPort.TxHeight + 1;

	if ( ! ( g = CreateContext( &CPPWindowGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < CPPWindow_CNT; lc++ ) {

		CopyMem((char * )&CPPWindowNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = &topaz8;
		ng.ng_LeftEdge  += offx;
		ng.ng_TopEdge   += offy;

		CPPWindowGadgets[ lc ] = g = CreateGadgetA((ULONG)CPPWindowGTypes[ lc ], g, &ng, ( struct TagItem * )&CPPWindowGTags[ tc ] );

		while( CPPWindowGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( CPPWindowMenus = CreateMenus( CPPWindowNewMenu, GTMN_FrontPen, 0L, TAG_DONE )))
		return( 3L );

	LayoutMenus( CPPWindowMenus, VisualInfo, GTMN_TextAttr, &topaz8, TAG_DONE );

	if ( ! ( CPPWindowWnd = OpenWindowTags( NULL,
				WA_Left,	CPPWindowLeft,
				WA_Top,		CPPWindowTop,
				WA_Width,	CPPWindowWidth,
				WA_Height,	CPPWindowHeight + offy,
				WA_IDCMP,	STRINGIDCMP|BUTTONIDCMP|INTEGERIDCMP|SLIDERIDCMP|CHECKBOXIDCMP|IDCMP_MENUPICK|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_SMART_REFRESH,
				WA_Gadgets,	CPPWindowGList,
				WA_Title,	CPPWindowWdt,
				WA_ScreenTitle,	"ScreenTitle",
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	SetMenuStrip( CPPWindowWnd, CPPWindowMenus );
	GT_RefreshWindow( CPPWindowWnd, NULL );

	return( 0L );
}

void CloseCPPWindowWindow( void )
{
	if ( CPPWindowMenus      ) {
		ClearMenuStrip( CPPWindowWnd );
		FreeMenus( CPPWindowMenus );
		CPPWindowMenus = NULL;	}

	if ( CPPWindowWnd        ) {
		CloseWindow( CPPWindowWnd );
		CPPWindowWnd = NULL;
	}

	if ( CPPWindowGList      ) {
		FreeGadgets( CPPWindowGList );
		CPPWindowGList = NULL;
	}
}

int HandleHelpIDCMP( void )
{
	struct IntuiMessage	*m;
	struct MenuItem		*n;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( HelpWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&HelpMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( HelpMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( HelpWnd );
				GT_EndRefresh( HelpWnd, TRUE );
				break;

				break;

			case	IDCMP_MENUPICK:
				while( HelpMsg.Code != MENUNULL ) {
					n = ItemAddress( HelpMenus, HelpMsg.Code );
					func = (void *)(GTMENUITEM_USERDATA( n ));
					running = func();
					HelpMsg.Code = n->NextSelect;
				}
				break;
		}
	}
	return( running );
}

int OpenHelpWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		offx = Scr->WBorLeft, offy = Scr->WBorTop + Scr->RastPort.TxHeight + 1;

	if ( ! ( HelpMenus = CreateMenus( HelpNewMenu, GTMN_FrontPen, 0L, TAG_DONE )))
		return( 3L );

	LayoutMenus( HelpMenus, VisualInfo, GTMN_TextAttr, &topaz8, TAG_DONE );

	if ( ! ( HelpWnd = OpenWindowTags( NULL,
				WA_Left,	HelpLeft,
				WA_Top,		HelpTop,
				WA_Width,	HelpWidth,
				WA_Height,	HelpHeight + offy,
				WA_IDCMP,	IDCMP_MENUPICK|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_SMART_REFRESH,
				WA_Title,	HelpWdt,
				WA_ScreenTitle,	"ScreenTitle",
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	SetMenuStrip( HelpWnd, HelpMenus );
	GT_RefreshWindow( HelpWnd, NULL );

	return( 0L );
}

void CloseHelpWindow( void )
{
	if ( HelpMenus      ) {
		ClearMenuStrip( HelpWnd );
		FreeMenus( HelpMenus );
		HelpMenus = NULL;	}

	if ( HelpWnd        ) {
		CloseWindow( HelpWnd );
		HelpWnd = NULL;
	}
}

