# Hint: See manual.


# 1. Applied to all requests
#  
#REMOVED
#====================
#temperature

#ADDED
#====================
#verbosity = low



# 2. Example: Removed from all requests where the model name is "gpt-5.6-luna"
#
#REMOVED gpt-5.6-luna
#====================
#verbosity

#ADDED gpt-5.6-luna
#====================
#top_p = 0.8



# 3. Example: Applied to all requests where model name starts with "gpt-5.6-"
#
#ADDED gpt-5.6-*
#====================
#top_p = 0.9
