/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

/* Copyright 2000 Kjetil S. Matheussen

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. */


#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_BS_from                             0
#define GD_BS_to                               1
#define GD_BS_select                           2
#define GD_BS_remove                           3

#define GDX_BS_from                            0
#define GDX_BS_to                              1
#define GDX_BS_select                          2
#define GDX_BS_remove                          3

#define BlockSelect_CNT 4

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *BlockSelectWnd;
extern struct Gadget        *BlockSelectGList;
extern struct Gadget        *BlockSelectGadgets[4];
extern UWORD                 BlockSelectLeft;
extern UWORD                 BlockSelectTop;
extern UWORD                 BlockSelectWidth;
extern UWORD                 BlockSelectHeight;
extern UBYTE                *BlockSelectWdt;
extern struct MinList        BS_from0List;
extern struct MinList        BS_to0List;
extern struct TextAttr       topaz8;
extern UWORD                 BlockSelectGTypes[];
extern struct NewGadget      BlockSelectNGad[];
extern ULONG                 BlockSelectGTags[];

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int OpenBlockSelectWindow( void );
extern void CloseBlockSelectWindow( void );
