/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

/* Copyright 2000 Kjetil S. Matheussen

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <proto/exec.h>
#include <proto/intuition.h>
#include <proto/gadtools.h>
#include <proto/graphics.h>
#include <proto/utility.h>
#include <string.h>

#include "Amiga_bs.h"

extern struct Screen         *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                   VisualInfo;
//struct Screen         *Scr;
//UBYTE                 *PubScreenName;
//APTR                   VisualInfo;
struct Window         *BlockSelectWnd = NULL;
struct Gadget         *BlockSelectGList = NULL;
struct Gadget         *BlockSelectGadgets[4];
UWORD                  BlockSelectLeft = 388;
UWORD                  BlockSelectTop = 72;
UWORD                  BlockSelectWidth = 324;
UWORD                  BlockSelectHeight = 208;
UBYTE                 *BlockSelectWdt = (UBYTE *)"Playlist Window";

extern struct MinList BS_from0List;

struct Node BS_from0Nodes[] = {
	( struct Node * )&BS_from0List.mlh_Tail, ( struct Node * )&BS_from0List.mlh_Head, 0, 0, "0 - NN" };

struct MinList BS_from0List = {
	( struct MinNode * )&BS_from0Nodes[0], ( struct MinNode * )NULL, ( struct MinNode * )&BS_from0Nodes[0] };

extern struct MinList BS_to0List;

struct Node BS_to0Nodes[] = {
	( struct Node * )&BS_to0List.mlh_Tail, ( struct Node * )&BS_to0List.mlh_Head, 0, 0, "0 - 0 - NN" };

struct MinList BS_to0List = {
	( struct MinNode * )&BS_to0Nodes[0], ( struct MinNode * )NULL, ( struct MinNode * )&BS_to0Nodes[0] };

extern struct TextAttr topaz8;

//struct TextAttr topaz8 = {
//	( STRPTR )"topaz.font", 8, 0x00, 0x01 };

UWORD BlockSelectGTypes[] = {
	LISTVIEW_KIND,
	LISTVIEW_KIND,
	BUTTON_KIND,
	BUTTON_KIND
};

struct NewGadget BlockSelectNGad[] = {
	0, 1, 130, 208, NULL, NULL, GD_BS_from, 0, NULL, NULL,
	171, 1, 127, 208, NULL, NULL, GD_BS_to, 0, NULL, NULL,
	133, 67, 37, 15, (UBYTE *)"=>", NULL, GD_BS_select, PLACETEXT_IN, NULL, NULL,
	133, 101, 37, 13, (UBYTE *)"<=", NULL, GD_BS_remove, PLACETEXT_IN, NULL, NULL
};

ULONG BlockSelectGTags[] = {
	(GTLV_ShowSelected), NULL, (TAG_DONE),
	(GTLV_ShowSelected), NULL, (TAG_DONE),
	(TAG_DONE),
	(TAG_DONE)
};

/*
int SetupScreen( void )
{
	if ( ! ( Scr = LockPubScreen( PubScreenName )))
		return( 1L );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		UnlockPubScreen( NULL, Scr );
		Scr = NULL;
	}
}
*/

int OpenBlockSelectWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		offx = Scr->WBorLeft, offy = Scr->WBorTop + Scr->RastPort.TxHeight + 1;

	if ( ! ( g = CreateContext( &BlockSelectGList ))){
		CloseBlockSelectWindow();
		return( 1L );
	}

	for( lc = 0, tc = 0; lc < BlockSelect_CNT; lc++ ) {

		CopyMem((char * )&BlockSelectNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = &topaz8;
		ng.ng_LeftEdge  += offx;
		ng.ng_TopEdge   += offy;

		BlockSelectGadgets[ lc ] = g = CreateGadgetA((ULONG)BlockSelectGTypes[ lc ], g, &ng, ( struct TagItem * )&BlockSelectGTags[ tc ] );

		while( BlockSelectGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g ){
			CloseBlockSelectWindow();
			return( 2L );
		}
	}

	if ( ! ( BlockSelectWnd = OpenWindowTags( NULL,
				WA_Left,	BlockSelectLeft,
				WA_Top,		BlockSelectTop,
				WA_Width,	BlockSelectWidth,
				WA_Height,	BlockSelectHeight + offy,
				WA_IDCMP,	LISTVIEWIDCMP | BUTTONIDCMP | IDCMP_NEWSIZE | IDCMP_REFRESHWINDOW | IDCMP_RAWKEY,
				WA_Flags,	WFLG_SIZEGADGET|WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_SMART_REFRESH,
				WA_Gadgets,	BlockSelectGList,
				WA_Title,	BlockSelectWdt,
				WA_MinWidth,	160,
				WA_MinHeight,	60,
				WA_MaxWidth,	720,
				WA_MaxHeight,	467,
				WA_AutoAdjust,	TRUE,
				WA_PubScreen,Scr,
				TAG_DONE )))
	{
		CloseBlockSelectWindow();
		return( 4L );
	}

	GT_RefreshWindow( BlockSelectWnd, NULL );

	return( 0L );
}

void CloseBlockSelectWindow( void )
{
	if ( BlockSelectWnd        ) {
		CloseWindow( BlockSelectWnd );
		BlockSelectWnd = NULL;
	}

	if ( BlockSelectGList      ) {
		FreeGadgets( BlockSelectGList );
		BlockSelectGList = NULL;
	}
}

