#OBJ4= mouse.o mouse_wtrack.o mouse_wtrackheader.o mouse_tempoheader.o mouse_wtrackborder.o mouse_temponodeborder.o mouse_fxarea.o mouse_pitches.o mouse_vellinenode.o mouse_vellineend.o mouse_vellinestart.o mouse_fxnode.o mouse_quantitize.o mouse_reltemposlider.o mouse_temponodes.o

#OBJ9= PEQrealline.o PEQline.o PEQmempool.o PEQblock.o PEQnotes.o PEQcommon.o PEQvelocities.o PEQpitches.o PEQ_calc.o PEQfxs.o PEQ_type.o PEQ_calc_64bit.o PEQ_clock.o PEQ_LPB.o PEQ_Signature.o PEQ_Beats.o

subtrack.o 
gfx_wtracks.o 
gfx_tempotrackheader.o
gfx_wtrackborder.o 
gfx_statusbar.o 
gfx_upperleft.o 
gfx_tempocolor.o 
trackreallines.o
nodeboxes.o
pitchnodes.o

pitchnodes.o:  $(BUILD_DEPENDENCIES) $(CD)pitchnodes.c
	$(CC) $(CD)pitchnodes.c $(OPT)


nodeboxes.o:  $(BUILD_DEPENDENCIES) $(CD)nodeboxes.c
	$(CC) $(CD)nodeboxes.c $(OPT)


trackreallines.o:  $(BUILD_DEPENDENCIES) $(CD)trackreallines.c
	$(CC) $(CD)trackreallines.c $(OPT)


subtrack.o:  $(BUILD_DEPENDENCIES) $(CD)subtrack.c
	$(CC) $(CD)subtrack.c $(OPT)


gfx_tempocolor.o:  $(BUILD_DEPENDENCIES)  $(CD)gfx_tempocolor.c
	$(CC)  $(CD)gfx_tempocolor.c $(OPT)


gfx_upperleft.o:  $(BUILD_DEPENDENCIES) $(CD)gfx_upperleft.c
	$(CC) $(CD)gfx_upperleft.c $(OPT)


gfx_statusbar.o:  $(BUILD_DEPENDENCIES) $(CD)gfx_statusbar.c
	$(CC) $(CD)gfx_statusbar.c $(OPT)


gfx_wtrackborder.o:  $(BUILD_DEPENDENCIES) $(CD)gfx_wtrackborder.c
	$(CC) $(CD)gfx_wtrackborder.c $(OPT)


gfx_wtracks.o:  $(BUILD_DEPENDENCIES) $(CD)gfx_wtracks.c 
	$(CC) $(CD)gfx_wtracks.c $(OPT)


gfx_tempotrackheader.o:  $(BUILD_DEPENDENCIES) $(CD)gfx_tempotrackheader.c
	$(CC) $(CD)gfx_tempotrackheader.c $(OPT)


mouse.o:  $(BUILD_DEPENDENCIES) $(CD)mouse.c
	$(CC) $(CD)mouse.c $(OPT)

mouse_wtrack.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_wtrack.c
	$(CC) $(CD)mouse_wtrack.c $(OPT)


mouse_temponodes.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_temponodes.c
	$(CC) $(CD)mouse_temponodes.c $(OPT)


mouse_wtrackborder.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_wtrackborder.c
	$(CC) $(CD)mouse_wtrackborder.c $(OPT)


mouse_temponodeborder.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_temponodeborder.c
	$(CC) $(CD)mouse_temponodeborder.c $(OPT)


mouse_fxarea.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_fxarea.c
	$(CC) $(CD)mouse_fxarea.c $(OPT)


mouse_pitches.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_pitches.c
	$(CC) $(CD)mouse_pitches.c $(OPT)


mouse_vellinenode.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_vellinenode.c
	$(CC) $(CD)mouse_vellinenode.c $(OPT)

mouse_vellinestart.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_vellinestart.c
	$(CC) $(CD)mouse_vellinestart.c $(OPT)

mouse_vellineend.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_vellineend.c
	$(CC) $(CD)mouse_vellineend.c $(OPT)

mouse_fxnode.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_fxnode.c
	$(CC) $(CD)mouse_fxnode.c $(OPT)

mouse_wtrackheader.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_wtrackheader.c
	$(CC) $(CD)mouse_wtrackheader.c $(OPT)


mouse_tempoheader.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_tempoheader.c
	$(CC) $(CD)mouse_tempoheader.c $(OPT)
mouse_quantitize.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_quantitize.c
	$(CC) $(CD)mouse_quantitize.c $(OPT)

mouse_reltemposlider.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_reltemposlider.c
	$(CC) $(CD)mouse_reltemposlider.c $(OPT)


PEQrealline.o:  $(BUILD_DEPENDENCIES) $(CD)PEQrealline.c $(CD)playerclass.h
	$(CC) $(CD)PEQrealline.c $(OPT) 

PEQline.o:  $(BUILD_DEPENDENCIES) $(CD)PEQline.c $(CD)playerclass.h
	$(CC) $(CD)PEQline.c $(OPT) 

PEQmempool.o:  $(BUILD_DEPENDENCIES) $(CD)PEQmempool.c $(CD)playerclass.h
	$(GCC) $(CD)PEQmempool.c $(OPT) 

PEQblock.o:  $(BUILD_DEPENDENCIES) $(CD)PEQblock.c $(CD)playerclass.h
	$(CC) $(CD)PEQblock.c $(OPT)

PEQnotes.o:  $(BUILD_DEPENDENCIES) $(CD)PEQnotes.c $(CD)playerclass.h
	$(CC) $(CD)PEQnotes.c $(OPT)

PEQcommon.o:  $(BUILD_DEPENDENCIES) $(CD)PEQcommon.c $(CD)playerclass.h
	$(CC) $(CD)PEQcommon.c $(OPT)

PEQvelocities.o:  $(BUILD_DEPENDENCIES) $(CD)PEQvelocities.c
	$(CC) $(CD)PEQvelocities.c $(OPT)

PEQpitches.o:  $(BUILD_DEPENDENCIES) $(CD)PEQpitches.c
	$(CC) $(CD)PEQpitches.c $(OPT)

PEQ_calc.o:  $(BUILD_DEPENDENCIES) $(CD)PEQ_calc.c
	$(CC) $(CD)PEQ_calc.c $(OPT)

PEQfxs.o:  $(BUILD_DEPENDENCIES) $(CD)PEQfxs.c
	$(CC) $(CD)PEQfxs.c $(OPT)

