#OBJ4= mouse.o mouse_wtrack.o mouse_wtrackheader.o mouse_tempoheader.o mouse_wtrackborder.o mouse_temponodeborder.o mouse_fxarea.o mouse_pitches.o mouse_vellinenode.o mouse_vellineend.o mouse_vellinestart.o mouse_fxnode.o mouse_quantitize.o mouse_reltemposlider.o mouse_temponodes.o

gfx_wtracks.o 
gfx_tempotrackheader.o
gfx_wtrackborder.o 

gfx_wtrackborder.o:  $(BUILD_DEPENDENCIES) $(CD)gfx_wtrackborder.c
	$(CC) $(CD)gfx_wtrackborder.c $(OPT)


gfx_wtracks.o:  $(BUILD_DEPENDENCIES) $(CD)gfx_wtracks.c 
	$(CC) $(CD)gfx_wtracks.c $(OPT)


gfx_tempotrackheader.o:  $(BUILD_DEPENDENCIES) $(CD)gfx_tempotrackheader.c
	$(CC) $(CD)gfx_tempotrackheader.c $(OPT)


mouse.o:  $(BUILD_DEPENDENCIES) $(CD)mouse.c
	$(CC) $(CD)mouse.c $(OPT)

mouse_wtrack.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_wtrack.c
	$(CC) $(CD)mouse_wtrack.c $(OPT)


mouse_temponodes.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_temponodes.c
	$(CC) $(CD)mouse_temponodes.c $(OPT)


mouse_wtrackborder.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_wtrackborder.c
	$(CC) $(CD)mouse_wtrackborder.c $(OPT)


mouse_temponodeborder.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_temponodeborder.c
	$(CC) $(CD)mouse_temponodeborder.c $(OPT)


mouse_fxarea.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_fxarea.c
	$(CC) $(CD)mouse_fxarea.c $(OPT)


mouse_pitches.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_pitches.c
	$(CC) $(CD)mouse_pitches.c $(OPT)


mouse_vellinenode.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_vellinenode.c
	$(CC) $(CD)mouse_vellinenode.c $(OPT)

mouse_vellinestart.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_vellinestart.c
	$(CC) $(CD)mouse_vellinestart.c $(OPT)

mouse_vellineend.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_vellineend.c
	$(CC) $(CD)mouse_vellineend.c $(OPT)

mouse_fxnode.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_fxnode.c
	$(CC) $(CD)mouse_fxnode.c $(OPT)

mouse_wtrackheader.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_wtrackheader.c
	$(CC) $(CD)mouse_wtrackheader.c $(OPT)


mouse_tempoheader.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_tempoheader.c
	$(CC) $(CD)mouse_tempoheader.c $(OPT)
mouse_quantitize.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_quantitize.c
	$(CC) $(CD)mouse_quantitize.c $(OPT)

mouse_reltemposlider.o:  $(BUILD_DEPENDENCIES) $(CD)mouse_reltemposlider.c
	$(CC) $(CD)mouse_reltemposlider.c $(OPT)

