// This file is automatically generated from gfx_op_queue.scm 

#ifndef VISUAL_OP_QUEUE_PROC_H 
#define VISUAL_OP_QUEUE_PROC_H 

extern LANGSPEC void QGFX_C2V_bitBlt(struct Tracker_Windows* window,int from_x1,int from_x2,int to_y); 
extern LANGSPEC void QGFX_C_DrawCursor(struct Tracker_Windows* window,int x1,int x2,int x3,int x4,int height,int y_pixmap); 
extern LANGSPEC void QGFX_P2V_bitBlt(struct Tracker_Windows* window,int from_x,int from_y,int to_x,int to_y,int width,int height); 
extern LANGSPEC void QGFX_P_FilledBox(struct Tracker_Windows* tvisual,int color,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_P_Box(struct Tracker_Windows* tvisual,int color,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_P_Line(struct Tracker_Windows* tvisual,int color,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_P_Point(struct Tracker_Windows* tvisual,int color,int x,int y); 
extern LANGSPEC void QGFX_P_Text(struct Tracker_Windows* tvisual,int color,char* text,int x,int y,int width,int flags); 
extern LANGSPEC void QGFX_Line(struct Tracker_Windows* tvisual,int color,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_All_Line(struct Tracker_Windows* tvisual,int color,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_Box(struct Tracker_Windows* tvisual,int color,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_FilledBox(struct Tracker_Windows* tvisual,int color,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_Slider_FilledBox(struct Tracker_Windows* tvisual,int color,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_All_FilledBox(struct Tracker_Windows* tvisual,int color,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_Text(struct Tracker_Windows* tvisual,int color,char* text,int x,int y,int width,int flags); 
extern LANGSPEC void QGFX_InitDrawCurrentLine(struct Tracker_Windows* tvisual,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_InitDrawCurrentLine2(struct Tracker_Windows* tvisual,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_DrawCursorPos(struct Tracker_Windows* tvisual,int fx,int fy,int fx2,int fy2,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_P_DrawTrackBorderSingle(struct Tracker_Windows* tvisual,int x,int y,int y2); 
extern LANGSPEC void QGFX_P_DrawTrackBorderDouble(struct Tracker_Windows* tvisual,int x,int y,int y2); 
extern LANGSPEC void QGFX_V_DrawTrackBorderSingle(struct Tracker_Windows* tvisual,int x,int y,int y2); 
extern LANGSPEC void QGFX_V_DrawTrackBorderDouble(struct Tracker_Windows* tvisual,int x,int y,int y2); 
extern LANGSPEC void QGFX_Scroll(struct Tracker_Windows* tvisual,int dx,int dy,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_P_Scroll(struct Tracker_Windows* tvisual,int dx,int dy,int x,int y,int x2,int y2); 
extern LANGSPEC void QGFX_ScrollDown(struct Tracker_Windows* tvisual,int dx,int dy,int x,int y,int x2,int y2); 

#endif 
