#!/bin/sh

HERE="$(dirname "$(readlink -f "$0")")"

# The radium helper programs (radium_error_message, radium_crashreporter,
# etc.) consider the installation to be faulty if QT_QPA_PLATFORM_PLUGIN_PATH
# is not set. It must point to the root directory of the Qt plugins.
# (run_radium_linux.sh checks that "$QT_QPA_PLATFORM_PLUGIN_PATH"/platforms/libqxcb.so exists.)
export QT_QPA_PLATFORM_PLUGIN_PATH="$HERE/usr/plugins"

exec "$HERE/usr/bin/radium" "$@"
